// The class manifest and the consumer helper (conformance kit, slice 1 —
// 20260826-036). Static analysis plus the helper run against fixtures; no DOM.
import { test } from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync, writeFileSync, mkdtempSync, mkdirSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';

import {
  buildManifest,
  definedClasses,
  documentedClasses,
  groupByComponent,
  iconIds,
  keyframeNames,
  tokenNames,
} from '../scripts/build-classes.mjs';
import { assertJunoClasses, junoClassesIn, loadJunoClasses } from '../tools/testing.mjs';

const manifest = loadJunoClasses();

test('the manifest ships and describes this build', () => {
  const pkg = JSON.parse(readFileSync('package.json', 'utf8'));
  assert.equal(manifest.version, pkg.version, 'manifest version is stale — rebuild');
  assert.ok(manifest.all.length > 200, `only ${manifest.all.length} classes found`);
  // exported, or a consumer cannot reach it
  assert.equal(pkg.exports['./classes.json'], './dist/classes.json');
  assert.equal(pkg.exports['./testing'], './tools/testing.mjs');
});

test('the manifest is regenerated by the build, not edited', () => {
  // Rebuilt from the same inputs it shipped from, the manifest must be
  // byte-identical. A hand-edited entry is the failure this whole slice
  // exists to make impossible.
  const fresh = buildManifest({
    css: readFileSync('dist/css/juno.css', 'utf8'),
    docs: 'docs',
    version: manifest.version,
    tokensCss: readFileSync('dist/css/juno-tokens.css', 'utf8'),
    spriteSvg: readFileSync('dist/icons/juno-icons.svg', 'utf8'),
  });
  assert.deepEqual(fresh, manifest);
});

test('a class is what has a RULE, not what a comment mentions', () => {
  // The distinction the whole manifest rests on. A doc block's usage example
  // names classes; counting those would make the manifest vouch for a class
  // with no rules, which is exactly the defect it detects.
  const css = `
    /* usage: <div class="juno-ghost-from-a-comment"> */
    .juno-real-one { color: red; }
    .juno-parent .juno-descendant { color: blue; }
    @media (pointer: coarse) { .juno-inside-a-media { color: green; } }
    .juno-has-a-value { content: '.juno-not-a-rule'; }
  `;
  const found = definedClasses(css);
  assert.ok(found.has('juno-real-one'));
  assert.ok(found.has('juno-parent'));
  assert.ok(found.has('juno-descendant'));
  assert.ok(found.has('juno-inside-a-media'), 'a rule nested in an at-rule is still a rule');
  assert.ok(found.has('juno-has-a-value'));
  assert.ok(!found.has('juno-ghost-from-a-comment'));
  assert.ok(!found.has('juno-not-a-rule'), 'a string in a declaration is not a selector');
});

test('an at-rule prelude is not a selector', () => {
  // `@keyframes juno-blink {` is a prelude carrying a juno-* name, so a
  // collector that does not skip at-rules files the animation as a CLASS —
  // and the manifest then vouches for a class with no rules, which is the one
  // thing it must never do. This is the case the earlier fixture missed: its
  // only at-rule was `@media (pointer: coarse)`, which contains no juno name,
  // so the mutation survived.
  const found = definedClasses('@keyframes juno-blink { 0% { opacity: 1; } }');
  assert.ok(!found.has('juno-blink'));
  // ...and the shipped manifest agrees
  for (const k of manifest.keyframes) {
    assert.ok(!manifest.all.includes(k), `${k} is a keyframe, not a class`);
  }
});

test('a custom property is not a class', () => {
  // `--juno-warning` and `.juno-warning` differ by two characters that a naive
  // matcher drops. Counting one made an earlier version of this matcher report
  // a component that had no defect.
  const found = definedClasses('.juno-x { color: var(--juno-warning); }');
  assert.ok(found.has('juno-x'));
  assert.ok(!found.has('juno-warning'));
});

test('the shipped typo classes are gone and the real ones are present', () => {
  // The two that motivated the slice (20260826-024). Named explicitly, because
  // "the manifest has lots of entries" is not the claim.
  assert.ok(manifest.all.includes('juno-seg__opt'));
  assert.ok(!manifest.all.includes('juno-seg__option'));
  assert.ok(manifest.all.includes('juno-list__row'));
  assert.ok(!manifest.all.includes('juno-list__item'));
});

test('every class named in a touch-default list is in the manifest', () => {
  // Slice 2 will generate these lists FROM the manifest; until then this is
  // the same guarantee stated as a check. Both mistyped members would fail
  // here.
  const base = readFileSync('src/css/base.css', 'utf8').replace(/\/\*[\s\S]*?\*\//g, ' ');
  const named = new Set();
  for (const m of base.matchAll(/:where\(([^)]*)\)/g)) {
    for (const c of m[1].matchAll(/\.(juno-[\w-]+)/g)) named.add(c[1]);
  }
  assert.ok(named.size > 5, 'the :where() lists were not found');
  assert.deepEqual(
    [...named].filter((c) => !manifest.all.includes(c)),
    [],
  );
});

test('components group into block, elements and modifiers', () => {
  const g = groupByComponent(['juno-seg', 'juno-seg__opt', 'juno-seg--sm', 'juno--warning']);
  assert.deepEqual(g.seg, {
    block: 'juno-seg',
    elements: ['juno-seg__opt'],
    modifiers: ['juno-seg--sm'],
  });
  assert.ok(!('warning' in g), 'a role utility is not a component');
});

test('the other juno namespaces are shipped too', () => {
  // Not classes — but a consumer writes them as bare strings, and a guard that
  // did not know them reported correct code. Measured on a real consumer: 8 of
  // 24 reports were of this kind.
  assert.ok(manifest.keyframes.includes('juno-blink'));
  assert.ok(manifest.icons.includes('juno-i'), 'the `#juno-i-${name}` template artifact');
  assert.ok(manifest.icons.some((i) => i.startsWith('juno-i-')));
  // a COMPONENT-LOCAL custom property, not just the global scale: reading only
  // juno-tokens.css missed these and reported three of them
  assert.ok(manifest.tokens.includes('juno-pillbar-gap'));
  assert.ok(manifest.tokens.includes('juno-size-tap-comfortable'));
});

test('keyframes, tokens and icon ids are read from their own artifacts', () => {
  assert.deepEqual([...keyframeNames('@keyframes juno-spin { }')], ['juno-spin']);
  assert.deepEqual([...tokenNames(':root { --juno-a: 1px; --other-b: 2px; }')], ['juno-a']);
  assert.deepEqual([...iconIds('<symbol id="juno-i-x"/>')].sort(), ['juno-i', 'juno-i-x']);
});

test('documented classes come from the docs tree', () => {
  const dir = mkdtempSync(join(tmpdir(), 'juno-docs-'));
  mkdirSync(join(dir, 'components'));
  writeFileSync(join(dir, 'components', 'x.md'), '`.juno-documented` and `.juno-also`');
  const found = documentedClasses(dir);
  assert.ok(found.has('juno-documented'));
  assert.ok(found.has('juno-also'));
});

test('public is a subset of all, and roles are always in it', () => {
  for (const p of manifest.public) assert.ok(manifest.all.includes(p), `${p} is not a class`);
  for (const r of manifest.roles) assert.ok(manifest.all.includes(r));
});

// ── the consumer helper ──────────────────────────────────────────────────

function fixture(files) {
  const dir = mkdtempSync(join(tmpdir(), 'juno-consumer-'));
  mkdirSync(join(dir, 'src'), { recursive: true });
  for (const [name, body] of Object.entries(files)) writeFileSync(join(dir, 'src', name), body);
  return dir;
}

test('the helper reports a name junoui ships nothing by', () => {
  const dir = fixture({ 'a.tsx': '<div className="juno-btn juno-modal-body" />' });
  assert.throws(() => assertJunoClasses(['src/**/*.tsx'], { cwd: dir }), /juno-modal-body/);
});

test('the helper accepts a token, a keyframe and an icon id', () => {
  // The three kinds that are not classes but ARE shipped names.
  const dir = fixture({
    'a.tsx': "junoPx('juno-pillbar-gap'); anim('juno-blink'); href={`#juno-i-${n}`}",
  });
  assert.doesNotThrow(() => assertJunoClasses(['src/**/*.tsx'], { cwd: dir }));
});

test('the helper ignores comments', () => {
  // A file that documents a typo in order to explain it must not be reported
  // for it — this repo's own guards do exactly that.
  const dir = fixture({ 'a.tsx': '// juno-modal-body was wrong\n<div className="juno-btn" />' });
  assert.doesNotThrow(() => assertJunoClasses(['src/**/*.tsx'], { cwd: dir }));
});

test('the helper honours an explicit allowance', () => {
  const dir = fixture({ 'a.tsx': '<div className="juno-mine" />' });
  assert.doesNotThrow(() =>
    assertJunoClasses(['src/**/*.tsx'], { cwd: dir, allowed: ['juno-mine'] }),
  );
});

test('the helper refuses to pass when it matched no files', () => {
  // A guard that inspected nothing and reported success is the failure mode
  // this kit exists to stop (CLAUDE.md §15, 2026-08-12). It has to be louder
  // than a pass.
  const dir = fixture({ 'a.tsx': '<div className="juno-btn" />' });
  assert.throws(() => assertJunoClasses(['nope/**/*.tsx'], { cwd: dir }), /vacuously/);
});

test('the stricter public surface is available and is stricter', () => {
  // `juno-sr-only` has a rule but no docs entry, which is why 'public' is NOT
  // the default — see tools/testing.mjs. Asserted here so the difference stays
  // a known quantity rather than a surprise.
  assert.ok(manifest.all.includes('juno-sr-only'));
  assert.ok(!manifest.public.includes('juno-sr-only'));
  const dir = fixture({ 'a.tsx': '<div className="juno-sr-only" />' });
  assert.doesNotThrow(() => assertJunoClasses(['src/**/*.tsx'], { cwd: dir }));
  assert.throws(
    () => assertJunoClasses(['src/**/*.tsx'], { cwd: dir, surface: 'public' }),
    /juno-sr-only/,
  );
});

test('junoClassesIn finds names in conditional and template positions', () => {
  // Where typos hide: not in the literal className="…" a matcher would parse.
  const names = junoClassesIn('`juno-btn ${on ? "juno-btn--ghost" : ""}`');
  assert.deepEqual(names, ['juno-btn', 'juno-btn--ghost']);
});
