// The class manifest and the consumer helper (conformance kit, slice 1 —
// 20260826-036). Static analysis plus the helper run against fixtures; no DOM.
import { test } from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync, writeFileSync, mkdtempSync, mkdirSync, readdirSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';

import {
  buildManifest,
  definedClasses,
  documentedClasses,
  groupByComponent,
  iconIds,
  keyframeNames,
  tokenNames,
} from '../scripts/build-classes.mjs';
import { assertJunoClasses, junoClassesIn, loadJunoClasses } from '../tools/testing.mjs';
import { TOUCH_SURFACES, touchDefaultsCss } from '../src/css/touch-surfaces.mjs';

const manifest = loadJunoClasses();
const components = () => readdirSync('src/css/components').map((f) => `src/css/components/${f}`);

test('the manifest ships and describes this build', () => {
  const pkg = JSON.parse(readFileSync('package.json', 'utf8'));
  assert.equal(manifest.version, pkg.version, 'manifest version is stale — rebuild');
  assert.ok(manifest.all.length > 200, `only ${manifest.all.length} classes found`);
  // exported, or a consumer cannot reach it
  assert.equal(pkg.exports['./classes.json'], './dist/classes.json');
  assert.equal(pkg.exports['./testing'], './tools/testing.mjs');
});

test('the manifest is regenerated by the build, not edited', () => {
  // Rebuilt from the same inputs it shipped from, the manifest must be
  // byte-identical. A hand-edited entry is the failure this whole slice
  // exists to make impossible.
  const fresh = buildManifest({
    css: readFileSync('dist/css/juno.css', 'utf8'),
    docs: 'docs',
    version: manifest.version,
    tokensCss: readFileSync('dist/css/juno-tokens.css', 'utf8'),
    spriteSvg: readFileSync('dist/icons/juno-icons.svg', 'utf8'),
  });
  assert.deepEqual(fresh, manifest);
});

test('a class is what has a RULE, not what a comment mentions', () => {
  // The distinction the whole manifest rests on. A doc block's usage example
  // names classes; counting those would make the manifest vouch for a class
  // with no rules, which is exactly the defect it detects.
  const css = `
    /* usage: <div class="juno-ghost-from-a-comment"> */
    .juno-real-one { color: red; }
    .juno-parent .juno-descendant { color: blue; }
    @media (pointer: coarse) { .juno-inside-a-media { color: green; } }
    .juno-has-a-value { content: '.juno-not-a-rule'; }
  `;
  const found = definedClasses(css);
  assert.ok(found.has('juno-real-one'));
  assert.ok(found.has('juno-parent'));
  assert.ok(found.has('juno-descendant'));
  assert.ok(found.has('juno-inside-a-media'), 'a rule nested in an at-rule is still a rule');
  assert.ok(found.has('juno-has-a-value'));
  assert.ok(!found.has('juno-ghost-from-a-comment'));
  assert.ok(!found.has('juno-not-a-rule'), 'a string in a declaration is not a selector');
});

test('an at-rule prelude is not a selector', () => {
  // `@keyframes juno-blink {` is a prelude carrying a juno-* name, so a
  // collector that does not skip at-rules files the animation as a CLASS —
  // and the manifest then vouches for a class with no rules, which is the one
  // thing it must never do. This is the case the earlier fixture missed: its
  // only at-rule was `@media (pointer: coarse)`, which contains no juno name,
  // so the mutation survived.
  const found = definedClasses('@keyframes juno-blink { 0% { opacity: 1; } }');
  assert.ok(!found.has('juno-blink'));
  // ...and the shipped manifest agrees
  for (const k of manifest.keyframes) {
    assert.ok(!manifest.all.includes(k), `${k} is a keyframe, not a class`);
  }
});

test('a custom property is not a class', () => {
  // `--juno-warning` and `.juno-warning` differ by two characters that a naive
  // matcher drops. Counting one made an earlier version of this matcher report
  // a component that had no defect.
  const found = definedClasses('.juno-x { color: var(--juno-warning); }');
  assert.ok(found.has('juno-x'));
  assert.ok(!found.has('juno-warning'));
});

test('the shipped typo classes are gone and the real ones are present', () => {
  // The two that motivated the slice (20260826-024). Named explicitly, because
  // "the manifest has lots of entries" is not the claim.
  assert.ok(manifest.all.includes('juno-seg__opt'));
  assert.ok(!manifest.all.includes('juno-seg__option'));
  assert.ok(manifest.all.includes('juno-list__row'));
  assert.ok(!manifest.all.includes('juno-list__item'));
});

test('every declared touch surface is a class some component defines', () => {
  // Slice 2's guarantee, and the one that makes the generated lists safe.
  //
  // NOT against the manifest: the manifest is built from the bundle, and the
  // bundle now CONTAINS the generated `:where()` lists — so a misspelled
  // member would appear as a selector, land in `all`, and vouch for itself.
  // Checked against the component sources instead, which is the non-circular
  // question: does a rule define this class anywhere other than the touch
  // block that names it?
  const defined = new Set();
  for (const f of components()) {
    for (const m of definedClasses(readFileSync(f, 'utf8'))) defined.add(m);
  }
  assert.deepEqual(
    TOUCH_SURFACES.filter((c) => !defined.has(c)),
    [],
    'declared as a touch surface but no component defines it',
  );
});

test('the two touch defaults are generated from one member list', () => {
  // The defect this replaces was TWO hand-maintained lists that had drifted
  // from each other: the tap-highlight set was a strict subset, missing four
  // rounded tappables, with nothing recording whether that was deliberate.
  const css = readFileSync('dist/css/juno.css', 'utf8');
  const names = (sel) => [...sel.matchAll(/\.(juno-[\w-]+)/g)].map((m) => m[1]).sort();

  const ta = /:where\(([^)]*)\)\s*\{\s*touch-action: manipulation/.exec(css);
  const th = /:where\(([^)]*)\)\s*\{\s*-webkit-tap-highlight-color/.exec(css);
  assert.ok(ta, 'the touch-action default is not in the bundle');
  assert.ok(th, 'the tap-highlight default is not in the bundle');

  assert.deepEqual(names(ta[1]), [...TOUCH_SURFACES].sort());
  assert.deepEqual(names(th[1]), names(ta[1]), 'the two lists have drifted apart again');

  // Membership, not just agreement. The two lists comparing equal to each
  // other and to TOUCH_SURFACES is satisfied by dropping a member from all
  // three — which is exactly the regression this change fixed, since the
  // shorter of the two hand-written lists was a strict subset. These four are
  // the ones it omitted; losing any of them again puts a UA highlight square
  // back behind a rounded control.
  for (const c of ['juno-chip', 'juno-pillbar__overflow', 'juno-seg__opt', 'juno-toggle-btn']) {
    assert.ok(TOUCH_SURFACES.includes(c), `${c} was dropped from the touch surfaces`);
  }
});

test('the touch defaults are not hand-written in base.css any more', () => {
  // A second copy would win or lose on source order and nobody would know.
  //
  // Scoped to `:where()` lists, not to the properties: base.css legitimately
  // declares touch-action on the opt-in gesture utilities
  // (.juno-gesture-surface, .juno-pan-x/-y), which are a different contract —
  // an element whose pointer events an app's own JS owns, not one of junoui's
  // tappable components.
  const base = readFileSync('src/css/base.css', 'utf8').replace(/\/\*[\s\S]*?\*\//g, ' ');
  for (const m of base.matchAll(/:where\([^)]*\)\s*\{([^}]*)\}/g)) {
    assert.ok(
      !/touch-action|-webkit-tap-highlight-color/.test(m[1]),
      'base.css hand-writes a touch default again; it is generated',
    );
  }
});

test('only the tap highlight is gated on a coarse pointer', () => {
  // touch-action must NOT be: a hybrid device (touch laptop, iPad with a
  // trackpad) reports a fine primary pointer while still taking touch input,
  // and the property is inert on a mouse anyway. The highlight only exists on
  // touch, so it is gated.
  // Asked of the GENERATED SOURCE, not of an index comparison in the bundle:
  // `indexOf('@media …', taAt)` finds the NEXT coarse block, so it stays
  // satisfied when the touch-action rule is itself wrapped in one. That
  // mutation survived until this was rewritten.
  const gen = touchDefaultsCss();
  const taAt = gen.indexOf('touch-action: manipulation');
  const mediaAt = gen.indexOf('@media');
  const thAt = gen.indexOf('-webkit-tap-highlight-color');
  assert.ok(taAt > -1 && mediaAt > -1 && thAt > -1, 'the generated layer lost a rule');
  assert.ok(taAt < mediaAt, 'touch-action got gated on pointer type');
  assert.ok(mediaAt < thAt, 'the tap highlight is no longer inside the coarse block');
  assert.match(gen.slice(mediaAt), /^@media \(pointer: coarse\)/);
});

test('components group into block, elements and modifiers', () => {
  const g = groupByComponent(['juno-seg', 'juno-seg__opt', 'juno-seg--sm', 'juno--warning']);
  assert.deepEqual(g.seg, {
    block: 'juno-seg',
    elements: ['juno-seg__opt'],
    modifiers: ['juno-seg--sm'],
  });
  assert.ok(!('warning' in g), 'a role utility is not a component');
});

test('the other juno namespaces are shipped too', () => {
  // Not classes — but a consumer writes them as bare strings, and a guard that
  // did not know them reported correct code. Measured on a real consumer: 8 of
  // 24 reports were of this kind.
  assert.ok(manifest.keyframes.includes('juno-blink'));
  assert.ok(manifest.icons.includes('juno-i'), 'the `#juno-i-${name}` template artifact');
  assert.ok(manifest.icons.some((i) => i.startsWith('juno-i-')));
  // a COMPONENT-LOCAL custom property, not just the global scale: reading only
  // juno-tokens.css missed these and reported three of them
  assert.ok(manifest.tokens.includes('juno-pillbar-gap'));
  assert.ok(manifest.tokens.includes('juno-size-tap-comfortable'));
});

test('keyframes, tokens and icon ids are read from their own artifacts', () => {
  assert.deepEqual([...keyframeNames('@keyframes juno-spin { }')], ['juno-spin']);
  assert.deepEqual([...tokenNames(':root { --juno-a: 1px; --other-b: 2px; }')], ['juno-a']);
  assert.deepEqual([...iconIds('<symbol id="juno-i-x"/>')].sort(), ['juno-i', 'juno-i-x']);
});

test('documentation is a usage position, not a mention', () => {
  // A selector or a code fence counts; a sentence does not. The first version
  // counted any occurrence, and a paragraph in conformance-kit.md written to
  // say "juno-sr-only is undocumented" promptly made juno-sr-only documented.
  // A heuristic a sentence about it can flip is not measuring documentation.
  const dir = mkdtempSync(join(tmpdir(), 'juno-docs-'));
  mkdirSync(join(dir, 'components'));
  writeFileSync(
    join(dir, 'components', 'x.md'),
    [
      '`.juno-selector`',
      '',
      '```html',
      '<div class="juno-in-a-fence">',
      '```',
      '',
      'the juno-prose-mention class',
    ].join('\n'),
  );
  const found = documentedClasses(dir);
  assert.ok(found.has('juno-selector'));
  assert.ok(found.has('juno-in-a-fence'));
  assert.ok(!found.has('juno-prose-mention'));
});

test('public is a subset of all, and roles are always in it', () => {
  for (const p of manifest.public) assert.ok(manifest.all.includes(p), `${p} is not a class`);
  for (const r of manifest.roles) assert.ok(manifest.all.includes(r));
});

// ── the consumer helper ──────────────────────────────────────────────────

function fixture(files) {
  const dir = mkdtempSync(join(tmpdir(), 'juno-consumer-'));
  mkdirSync(join(dir, 'src'), { recursive: true });
  for (const [name, body] of Object.entries(files)) writeFileSync(join(dir, 'src', name), body);
  return dir;
}

test('the helper reports a name junoui ships nothing by', () => {
  const dir = fixture({ 'a.tsx': '<div className="juno-btn juno-modal-body" />' });
  assert.throws(() => assertJunoClasses(['src/**/*.tsx'], { cwd: dir }), /juno-modal-body/);
});

test('the helper accepts a token, a keyframe and an icon id', () => {
  // The three kinds that are not classes but ARE shipped names.
  const dir = fixture({
    'a.tsx': "junoPx('juno-pillbar-gap'); anim('juno-blink'); href={`#juno-i-${n}`}",
  });
  assert.doesNotThrow(() => assertJunoClasses(['src/**/*.tsx'], { cwd: dir }));
});

test('the helper ignores comments', () => {
  // A file that documents a typo in order to explain it must not be reported
  // for it — this repo's own guards do exactly that.
  const dir = fixture({ 'a.tsx': '// juno-modal-body was wrong\n<div className="juno-btn" />' });
  assert.doesNotThrow(() => assertJunoClasses(['src/**/*.tsx'], { cwd: dir }));
});

test('the helper honours an explicit allowance', () => {
  const dir = fixture({ 'a.tsx': '<div className="juno-mine" />' });
  assert.doesNotThrow(() =>
    assertJunoClasses(['src/**/*.tsx'], { cwd: dir, allowed: ['juno-mine'] }),
  );
});

test('the helper refuses to pass when it matched no files', () => {
  // A guard that inspected nothing and reported success is the failure mode
  // this kit exists to stop (CLAUDE.md §15, 2026-08-12). It has to be louder
  // than a pass.
  const dir = fixture({ 'a.tsx': '<div className="juno-btn" />' });
  assert.throws(() => assertJunoClasses(['nope/**/*.tsx'], { cwd: dir }), /vacuously/);
});

test('the stricter public surface is available and is stricter', () => {
  // `juno-sr-only` has a rule but no docs entry, which is why 'public' is NOT
  // the default — see tools/testing.mjs. Asserted here so the difference stays
  // a known quantity rather than a surprise.
  assert.ok(manifest.all.includes('juno-sr-only'));
  assert.ok(!manifest.public.includes('juno-sr-only'));
  const dir = fixture({ 'a.tsx': '<div className="juno-sr-only" />' });
  assert.doesNotThrow(() => assertJunoClasses(['src/**/*.tsx'], { cwd: dir }));
  assert.throws(
    () => assertJunoClasses(['src/**/*.tsx'], { cwd: dir, surface: 'public' }),
    /juno-sr-only/,
  );
});

test('junoClassesIn does not return custom-property references', () => {
  // `--juno-x` and `.juno-x` differ by the two characters in front, and
  // `junoClassesIn` is a CLASS matcher — a caller reading its output is
  // entitled to that. Pinned directly because the assertion is otherwise
  // masked: a leaked `--juno-warning` reads as `juno-warning`, which is a
  // shipped token, so assertJunoClasses would not report it and the mutation
  // that drops the lookbehind survived.
  assert.deepEqual(junoClassesIn('color: var(--juno-warning);'), []);
  assert.deepEqual(junoClassesIn('var(--juno-not-a-real-token)'), []);
  assert.deepEqual(junoClassesIn('<div className="juno-warning" />'), ['juno-warning']);
});

test('junoClassesIn finds names in conditional and template positions', () => {
  // Where typos hide: not in the literal className="…" a matcher would parse.
  const names = junoClassesIn('`juno-btn ${on ? "juno-btn--ghost" : ""}`');
  assert.deepEqual(names, ['juno-btn', 'juno-btn--ghost']);
});
