// ════════════════════════════════════════════════════════════════════════
//  junoui — Style Dictionary build
// ════════════════════════════════════════════════════════════════════════
//  One DTCG source (tokens/**) → every platform output. Run: `npm run build`.
//
//  Web (CSS) keeps literal oklch() — browsers render it natively and it is
//  the authored source of truth. Native targets (Android / iOS / Flutter)
//  cannot parse oklch(), so colors are converted to sRGB hex here with a
//  dependency-free OKLab→sRGB transform.
// ════════════════════════════════════════════════════════════════════════

import StyleDictionary from 'style-dictionary';
import { toHex } from './scripts/color.mjs';

// ── value + name helpers ────────────────────────────────────────────────
const val = (t) => t.original?.$value ?? t.$value ?? t.value;
const isColorToken = (t) => t.path[0] === 'color';
const coreTokens = (d) => d.allTokens.filter((t) => !isColorToken(t));
const colorTokens = (d) => d.allTokens.filter((t) => isColorToken(t));

// CSS/SCSS variable name from token path: space.16 → juno-space-16
const flatName = (t) => 'juno-' + t.path.join('-');
// camelCase identifier: color.standard.dark.nominal → colorStandardDarkNominal.
// Hyphens in a segment (e.g. data-dim) are word breaks so native identifiers
// stay valid: ['standard','dark','data-dim'] → standardDarkDataDim.
const camel = (parts) =>
  parts
    .flatMap((p) => String(p).split('-'))
    .map((w, i) => (i === 0 ? w : w.charAt(0).toUpperCase() + w.slice(1)))
    .join('');

// ── group color tokens into { palette: { mode: { role: value } } } ──────
function byTheme(d, transform = (x) => x) {
  const themes = {};
  for (const t of colorTokens(d)) {
    const [, palette, mode, role] = t.path;
    ((themes[palette] ??= {})[mode] ??= {})[role] = transform(val(t));
  }
  return themes;
}
const ROLES = [
  'nominal',
  'active',
  'target',
  'caution',
  'warning',
  'data',
  'data-dim',
  'label',
  'muted',
  'border',
  'border-strong',
  's0',
  's1',
  's2',
  's3',
];

// ════════════════════════════════════════════════════════════════════════
//  Formats
// ════════════════════════════════════════════════════════════════════════

// CSS — core vars on :root, semantic color vars per palette/mode selector.
// Default (attribute-less) :root resolves to standard / dark.
StyleDictionary.registerFormat({
  name: 'css/juno-themed',
  format: ({ dictionary }) => {
    const semantic = (theme) => ROLES.map((r) => `  --juno-${r}: ${theme[r]};`).join('\n');
    const themes = byTheme(dictionary);
    const head = `/**
 * junoui design tokens — CSS custom properties.
 * Core tokens live on :root. Semantic color roles switch with
 * [data-juno-palette] + [data-juno-mode]; defaults are standard / dark.
 * Generated by Style Dictionary — do not edit by hand.
 */\n`;
    // Font sizes route through --juno-font-scale (default 1) so a single
    // [data-juno-text] switch can scale all type without touching density.
    const isFontSize = (t) => t.path[0] === 'font' && t.path[1] === 'size';
    const coreVal = (t) => (isFontSize(t) ? `calc(${val(t)} * var(--juno-font-scale, 1))` : val(t));
    let out = head + ':root {\n';
    out +=
      coreTokens(dictionary)
        .map((t) => `  --${flatName(t)}: ${coreVal(t)};`)
        .join('\n') + '\n\n';
    out += semantic(themes.standard.dark) + '\n}\n';
    for (const palette of Object.keys(themes)) {
      // palette set but no mode → dark baseline in that palette (not standard's)
      out += `\n:root[data-juno-palette="${palette}"]:not([data-juno-mode]) {\n`;
      out += semantic(themes[palette].dark) + '\n}\n';
      for (const mode of Object.keys(themes[palette])) {
        out += `\n:root[data-juno-palette="${palette}"][data-juno-mode="${mode}"] {\n`;
        out += semantic(themes[palette][mode]) + '\n}\n';
      }
    }
    // system preference — no data-juno-mode set → follow the OS color scheme.
    // Dark is the attribute-less baseline above; light rides the media query.
    const mediaIndent = (s) => s.replace(/^ {2}/gm, '    ');
    out += '\n/* no data-juno-mode → follow the system color scheme */\n';
    out += '@media (prefers-color-scheme: light) {\n';
    out += '  :root:not([data-juno-mode]) {\n';
    out += mediaIndent(semantic(themes.standard.light)) + '\n  }\n';
    for (const palette of Object.keys(themes)) {
      out += `\n  :root[data-juno-palette="${palette}"]:not([data-juno-mode]) {\n`;
      out += mediaIndent(semantic(themes[palette].light)) + '\n  }\n';
    }
    out += '}\n';
    return out;
  },
});

// SCSS — flat !default variables (every token, every theme).
// CSS @custom-media — media queries cannot read custom properties, so the
// breakpoint tokens were only reachable by hand-copying their literals (both
// junoui and its consumers hardcoded `767.98px`). Emitting named queries from
// the same token makes the breakpoint the actual source of truth.
// Shipped as its OWN file, not folded into juno-tokens.css: @custom-media is
// Media Queries L5 and has no native support anywhere — it needs a build step
// (postcss-custom-media), so consumers opt in rather than carry dead at-rules.
StyleDictionary.registerFormat({
  name: 'css/juno-custom-media',
  format: ({ dictionary }) => {
    const bps = dictionary.allTokens.filter((t) => t.path[0] === 'bp');
    const head = `/**
 * junoui breakpoints as named media queries.
 * REQUIRES a build step — \`@custom-media\` has no native browser support:
 *   postcss([ require('postcss-custom-media') ])
 * Not running postcss? Use the plain literal shown in each comment instead.
 * Generated by Style Dictionary — do not edit by hand.
 */\n\n`;
    // `below` is exclusive of the breakpoint itself. 0.02px (not 1px) is the
    // standard guard: it is finer than any fractional-pixel zoom level, so the
    // two halves never overlap and never leave a gap between them.
    const below = (v) => `${parseFloat(v) - 0.02}px`;
    return (
      head +
      bps
        .map((t) => {
          const name = t.path.slice(1).join('-');
          const from = val(t);
          return (
            `/* ${name} = ${from}${t.$description ? ` — ${t.$description.replace(/^≥ /, '')}` : ''}\n` +
            `   no postcss? write (width <= ${below(from)}) / (width >= ${from}) */\n` +
            `@custom-media --juno-below-${name} (width <= ${below(from)});\n` +
            `@custom-media --juno-from-${name} (width >= ${from});`
          );
        })
        .join('\n\n') +
      '\n'
    );
  },
});

StyleDictionary.registerFormat({
  name: 'scss/aero',
  format: ({ dictionary }) => {
    const head = '// junoui design tokens — SCSS variables. Generated; do not edit.\n\n';
    return (
      head +
      dictionary.allTokens.map((t) => `$${flatName(t)}: ${val(t)} !default;`).join('\n') +
      '\n'
    );
  },
});

// JS — nested TOKENS[palette][mode][role] (back-compatible) + CORE tree.
function nestedCore(d) {
  const root = {};
  for (const t of coreTokens(d)) {
    let node = root;
    t.path.forEach((seg, i) => {
      if (i === t.path.length - 1) node[seg] = val(t);
      else node = node[seg] ??= {};
    });
  }
  return root;
}
StyleDictionary.registerFormat({
  name: 'js/aero',
  format: ({ dictionary }) => {
    const TOKENS = byTheme(dictionary);
    const CORE = nestedCore(dictionary);
    return `// junoui design tokens — JS. Generated by Style Dictionary; do not edit.
export const TOKENS = ${JSON.stringify(TOKENS, null, 2)};

export const CORE = ${JSON.stringify(CORE, null, 2)};

export function getTokens(palette = 'standard', mode = 'dark') {
  return (TOKENS[palette] || TOKENS.standard)[mode] || TOKENS.standard.dark;
}

export default { TOKENS, CORE, getTokens };
`;
  },
});
StyleDictionary.registerFormat({
  name: 'ts/juno-dts',
  format: () =>
    `// junoui design tokens — types. Generated; do not edit.
export type JunoPalette = 'standard' | 'colorblind' | 'soft';
export type JunoMode = 'dark' | 'light';
export type JunoRole =
  ${ROLES.map((r) => `'${r}'`).join(' | ')};
export type JunoTheme = Record<JunoRole, string>;
export const TOKENS: Record<JunoPalette, Record<JunoMode, JunoTheme>>;
export const CORE: Record<string, unknown>;
export function getTokens(palette?: JunoPalette, mode?: JunoMode): JunoTheme;
declare const _default: { TOKENS: typeof TOKENS; CORE: typeof CORE; getTokens: typeof getTokens };
export default _default;
`,
});

// JSON — clean W3C DTCG tree (any tool can read it).
StyleDictionary.registerFormat({
  name: 'json/juno-dtcg',
  format: ({ dictionary }) => {
    const root = {};
    for (const t of dictionary.allTokens) {
      let node = root;
      t.path.forEach((seg, i) => {
        if (i === t.path.length - 1) {
          node[seg] = { $value: val(t), $type: t.$type ?? t.type };
          if (t.$description ?? t.description)
            node[seg].$description = t.$description ?? t.description;
        } else node = node[seg] ??= {};
      });
    }
    return JSON.stringify(root, null, 2) + '\n';
  },
});

// Android — colors.xml (hex, every theme) + dimens.xml (core dimensions).
StyleDictionary.registerFormat({
  name: 'android/juno-colors',
  format: ({ dictionary }) => {
    const rows = colorTokens(dictionary)
      .map(
        (t) =>
          `  <color name="${t.path.slice(1).join('_').replace(/-/g, '_')}">${toHex(val(t))}</color>`,
      )
      .join('\n');
    return `<?xml version="1.0" encoding="utf-8"?>\n<!-- junoui color tokens. Generated; do not edit. -->\n<resources>\n${rows}\n</resources>\n`;
  },
});
StyleDictionary.registerFormat({
  name: 'android/juno-dimens',
  format: ({ dictionary }) => {
    const dims = coreTokens(dictionary).filter((t) => /px$/.test(String(val(t))));
    const unit = (t) => (t.path[0] === 'font' && t.path[1] === 'size' ? 'sp' : 'dp');
    const rows = dims
      .map((t) => `  <dimen name="${t.path.join('_')}">${parseFloat(val(t))}${unit(t)}</dimen>`)
      .join('\n');
    return `<?xml version="1.0" encoding="utf-8"?>\n<!-- junoui dimension tokens. Generated; do not edit. -->\n<resources>\n${rows}\n</resources>\n`;
  },
});

// iOS — Swift enum of UIColor + CGFloat constants.
StyleDictionary.registerFormat({
  name: 'ios/juno-swift',
  format: ({ dictionary }) => {
    const colorLines = colorTokens(dictionary).map((t) => {
      const h = toHex(val(t)).slice(1);
      const id = camel(t.path.slice(1));
      return `    public static let ${id} = JunoColor.hex(0x${h})`;
    });
    const dimLines = coreTokens(dictionary)
      .filter((t) => /px$/.test(String(val(t))))
      .map((t) => `    public static let ${camel(t.path)}: CGFloat = ${parseFloat(val(t))}`);
    return `// junoui design tokens — Swift. Generated; do not edit.
import UIKit

public enum JunoColor {
    static func hex(_ v: UInt32) -> UIColor {
        UIColor(red: CGFloat((v >> 16) & 0xFF) / 255,
                green: CGFloat((v >> 8) & 0xFF) / 255,
                blue: CGFloat(v & 0xFF) / 255, alpha: 1)
    }
}

public enum JunoTokens {
${colorLines.join('\n')}

${dimLines.join('\n')}
}
`;
  },
});

// Flutter — Dart class of Color + double constants.
StyleDictionary.registerFormat({
  name: 'flutter/juno-dart',
  format: ({ dictionary }) => {
    const colorLines = colorTokens(dictionary).map((t) => {
      const h = toHex(val(t)).slice(1);
      const id = camel(t.path.slice(1));
      return `  static const Color ${id} = Color(0xFF${h});`;
    });
    const dimLines = coreTokens(dictionary)
      .filter((t) => /px$/.test(String(val(t))))
      .map((t) => `  static const double ${camel(t.path)} = ${parseFloat(val(t))};`);
    return `// junoui design tokens — Dart / Flutter. Generated; do not edit.
import 'dart:ui';

class JunoTokens {
  JunoTokens._();

${colorLines.join('\n')}

${dimLines.join('\n')}
}
`;
  },
});

// ════════════════════════════════════════════════════════════════════════
//  Build — single source, no transforms (values stay literal / authored).
// ════════════════════════════════════════════════════════════════════════
const sd = new StyleDictionary({
  source: ['tokens/**/*.json'],
  // Output names are derived from full token paths inside each format, so
  // SD's leaf-name collision check (nominal/active/… repeat per theme) is
  // expected and harmless. Quiet it.
  log: { warnings: 'disabled' },
  platforms: {
    css: {
      transforms: [],
      buildPath: 'dist/css/',
      files: [
        { destination: 'juno-tokens.css', format: 'css/juno-themed' },
        { destination: 'juno-custom-media.css', format: 'css/juno-custom-media' },
      ],
    },
    scss: {
      transforms: [],
      buildPath: 'dist/scss/',
      files: [{ destination: '_juno-tokens.scss', format: 'scss/aero' }],
    },
    js: {
      transforms: [],
      buildPath: 'dist/js/',
      files: [
        { destination: 'tokens.js', format: 'js/aero' },
        { destination: 'tokens.d.ts', format: 'ts/juno-dts' },
      ],
    },
    json: {
      transforms: [],
      buildPath: 'dist/json/',
      files: [{ destination: 'tokens.json', format: 'json/juno-dtcg' }],
    },
    android: {
      transforms: [],
      buildPath: 'dist/android/',
      files: [
        { destination: 'colors.xml', format: 'android/juno-colors' },
        { destination: 'dimens.xml', format: 'android/juno-dimens' },
      ],
    },
    ios: {
      transforms: [],
      buildPath: 'dist/ios/',
      files: [{ destination: 'JunoTokens.swift', format: 'ios/juno-swift' }],
    },
    flutter: {
      transforms: [],
      buildPath: 'dist/flutter/',
      files: [{ destination: 'juno_tokens.dart', format: 'flutter/juno-dart' }],
    },
  },
});

await sd.cleanAllPlatforms();
await sd.buildAllPlatforms();
console.log('✓ junoui tokens built → dist/');
