// ════════════════════════════════════════════════════════════════════════
//  junoui — token reference generator
// ════════════════════════════════════════════════════════════════════════
//  Reads the built token module and emits docs/tokens-reference.md: every
//  token with its value and per-platform identifier, plus resolved sRGB hex
//  for colors. This is the document a designer in Figma/Sketch/any non-CSS
//  tool reads to get exact values. Run: `npm run gen-docs`.
// ════════════════════════════════════════════════════════════════════════

import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { TOKENS, CORE } from '../dist/js/tokens.js';
import { toHex } from './color.mjs';

export const REFERENCE_PATH = 'docs/tokens-reference.md';

const PALETTES = Object.keys(TOKENS);
const MODES = ['dark', 'light'];
const ROLES = [
  'nominal',
  'active',
  'target',
  'caution',
  'warning',
  'data',
  'data-dim',
  'label',
  'muted',
  'border',
  'border-strong',
  's0',
  's1',
  's2',
  's3',
];

const camel = (parts) =>
  parts.map((p, i) => (i === 0 ? p : p[0].toUpperCase() + p.slice(1))).join('');

// Flatten CORE tree → [ [pathArray, value], ... ]
function flatten(obj, path = []) {
  const out = [];
  for (const [k, v] of Object.entries(obj)) {
    if (v && typeof v === 'object') out.push(...flatten(v, [...path, k]));
    else out.push([[...path, k], v]);
  }
  return out;
}

export function buildReference() {
  let md = `<!-- GENERATED by scripts/gen-docs.mjs — do not edit by hand. Run \`npm run gen-docs\`. -->

# Token reference

Every junoui token with its value and the identifier to use on each platform.
Colors show the authored value and the resolved sRGB hex (use the hex in any
tool that does not understand \`oklch()\`).

## How names map across platforms

| Platform | Pattern | Example (\`color.standard.dark.nominal\`) |
|---|---|---|
| CSS — semantic | \`var(--juno-<role>)\` (switches with theme attrs) | \`var(--juno-nominal)\` |
| SCSS | \`$juno-color-<palette>-<mode>-<role>\` | \`$juno-color-standard-dark-nominal\` |
| JS / TS | \`TOKENS.<palette>.<mode>.<role>\` | \`TOKENS.standard.dark.nominal\` |
| JSON (DTCG) | \`color.<palette>.<mode>.<role>\` | \`color.standard.dark.nominal\` |
| Android | \`@color/<palette>_<mode>_<role>\` | \`@color/standard_dark_nominal\` |
| iOS (Swift) | \`JunoTokens.<camelCase>\` | \`JunoTokens.standardDarkNominal\` |
| Flutter (Dart) | \`JunoTokens.<camelCase>\` | \`JunoTokens.standardDarkNominal\` |

Core tokens (spacing, radius, typography, …) use \`--juno-<path-joined-by->\`,
e.g. \`space.16\` → \`var(--juno-space-16)\`, \`@dimen/space_16\`, \`JunoTokens.space16\`.

`;

  // ── Color roles ──────────────────────────────────────────────────────────
  md += `## Color roles\n\nColor encodes status, never decoration. Each role has exactly one meaning.\n\n`;
  for (const p of PALETTES) {
    md += `### Palette: ${p}\n\n`;
    md += `| Role | Dark value | Dark hex | Light value | Light hex |\n|---|---|---|---|---|\n`;
    for (const role of ROLES) {
      const dv = TOKENS[p].dark[role],
        lv = TOKENS[p].light[role];
      md += `| \`${role}\` | \`${dv}\` | \`${toHex(dv)}\` | \`${lv}\` | \`${toHex(lv)}\` |\n`;
    }
    md += '\n';
  }

  // ── Core tokens ────────────────────────────────────────────────────────────
  const core = flatten(CORE);
  const groups = {};
  for (const [path, value] of core) (groups[path[0]] ??= []).push([path, value]);

  md += `## Core tokens\n\n`;
  const TITLES = {
    space: 'Spacing',
    radius: 'Radius',
    border: 'Borders',
    size: 'Sizing',
    font: 'Typography',
    bp: 'Breakpoints',
    motion: 'Motion',
    z: 'Z-index',
    shadow: 'Elevation',
    opacity: 'Opacity',
  };
  for (const key of Object.keys(groups)) {
    md += `### ${TITLES[key] ?? key}\n\n`;
    md += `| Token | Value | CSS variable | Flutter / iOS |\n|---|---|---|---|\n`;
    for (const [path, value] of groups[key]) {
      const dotted = path.join('.');
      const cssVar = `--juno-${path.join('-')}`;
      const native = camel(path);
      md += `| \`${dotted}\` | \`${value}\` | \`var(${cssVar})\` | \`JunoTokens.${native}\` |\n`;
    }
    md += '\n';
  }

  return md;
}

// Run directly → write the file. Imported → just expose buildReference().
if (process.argv[1] === fileURLToPath(import.meta.url)) {
  writeFileSync(REFERENCE_PATH, buildReference());
  console.log(`✓ wrote ${REFERENCE_PATH}`);
}
